[build]
  base = "Frontend"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://trello-backend-production-6c60.up.railway.app/api"
  VITE_SOCKET_URL = "https://trello-backend-production-6c60.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200